/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2020-06-26 06:24:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.stock;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import database.DBAccess;

public final class stocklist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("database.DBAccess");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=Shift_JIS");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

// 内容: データベースにアクセスする

// MyDBAccess のインスタンスを生成する
DBAccess db = new DBAccess();

// データベースへのアクセス
db.open();

// メンバーを取得
ResultSet rs = db.getResultSet("select * from price where date = now()::date");

// メンバー一覧表示用のテーブル
String tableHTML = "<table border=1>";
tableHTML += "<tr bgcolor=\"000080\"><td><font color=\"white\">銘柄コード</font></td>"
    + "<td><font color=\"white\">日付</font></td>"
    + "<td><font color=\"white\">始値</font></td>"
    + "<td><font color=\"white\">終値</font></td>"
    + "<td><font color=\"white\">出来高</font></td>";

// 取得された各結果に対しての処理
while(rs.next()) {

    int stockcode = rs.getInt("stock_code");
    Date date = rs.getDate("date");
    int openprice = rs.getInt("open_price");
    int closeprice = rs.getInt("closing_price");
    int volume = rs.getInt("volume");

//    // 文字コードを EUC_JP からUnicode へ変換
//    japan_name = new String(name.getBytes("8859_1"), "EUC_JP");
//    kana = new String(kana.getBytes("8859_1"), "EUC_JP");

    // テーブル用HTMLを作成
    tableHTML += "<tr><td align=\"right\">" + stockcode + "</td>"
              + "<td>" + date + "</td><td>" + openprice + "</td>"
              + "<td>" + closeprice + "</td>"
              +"<td>" + volume + "</td></tr>";
}

tableHTML += "</table>";

// データベースへのコネクションを閉じる
db.close();


      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\t<title>QUICK証券</title>\r\n");
      out.write("\r\n");
      out.write("\t<meta charset=\"Shift_JIS\" lang=\"ja\">\r\n");
      out.write(" \t<link rel=\"stylesheet\" href=\"./css/top.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/highlight.js.css\">\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"./css/swiper.min.css\">\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"./css/style.css\">\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"./css/sample.css\">\r\n");
      out.write("\t <link rel=\"stylesheet\" href=\"./css/sample02.css\">\r\n");
      out.write("\r\n");
      out.write("\t <script src=\"./js/highlight.js\"></script>\r\n");
      out.write("\t <script src=\"./js/highlightjs-line-numbers.min.js\"></script>\r\n");
      out.write("\t <script src=\"./js/swiper.min.js\"></script>\r\n");
      out.write("\t <script src=\"./js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <nav id=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <ul class=\"navlinks\">\r\n");
      out.write("          <li><a href=\"index.html\">Homepage</a></li>\r\n");
      out.write("          <li><a href=\"index.html\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"index.html\">Projects</a></li>\r\n");
      out.write("          <li><a href=\"index.html\">The Team</a></li>\r\n");
      out.write("          <li><a href=\"index.html\">Contacts</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <header id=\"heading\">\r\n");
      out.write("      <div class=\"container text-center\">\r\n");
      out.write("        <h1>QUICK証券</h1>\r\n");
      out.write("        <h4>But this is just a sample demo layout, don't get too excited!</h4>\r\n");
      out.write("\r\n");
      out.write("        <p><a href=\"index.html\" class=\"btn btn-large btn-inverse\">Check out our features</a></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"l-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  <div class=\"c-container\">\r\n");
      out.write("\t    <div class=\"sample sample02\">\r\n");
      out.write("\t      <div class=\"swiper-container\">\r\n");
      out.write("\t        <div class=\"swiper-wrapper\">\r\n");
      out.write("\t          <div class=\"swiper-slide\">\r\n");
      out.write("\t            <div class=\"sample02-inner\">\r\n");
      out.write("\t              <p><朝日>日産がＳＵＶ「キックス」発売　国内で１０年ぶり新車種</p>\r\n");
      out.write("\t                <!-- <br class=\"u-d-n u-d-i-md\">うつくしい森で飾られたモリーオ市、郊外のぎらぎらひかる草の波。 -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\r\n");
      out.write("\t          <div class=\"swiper-slide\">\r\n");
      out.write("\t            <div class=\"sample02-inner\">\r\n");
      out.write("\t              <p><Nikkei>◇Nissan Motor: New HV released on 30th. Three expectations for this.</p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\r\n");
      out.write("\t          <div class=\"swiper-slide\">\r\n");
      out.write("\t            <div class=\"sample02-inner\">\r\n");
      out.write("\t              <p><TECH>★日経平均寄与度ﾗﾝｷﾝｸﾞ(大引)―値上り59、値下り163銘柄</p>\r\n");
      out.write("\t                <!-- <br class=\"u-d-n u-d-i-md\">しずかにあの年のイーハトーヴォの五月から十月までを書きつけましょう。 -->\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t          </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t        <div class=\"swiper-button-prev\">\r\n");
      out.write("\t          <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 27 44\">\r\n");
      out.write("\t            <path class=\"c-arrow c-arrow-prev\" d=\"M0,22L22,0l2.1,2.1L4.2,22l19.9,19.9L22,44L0,22L0,22L0,22z\" />\r\n");
      out.write("\t          </svg>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"swiper-button-next\">\r\n");
      out.write("\t          <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 27 44\">\r\n");
      out.write("\t            <path class=\"c-arrow c-arrow-next\" d=\"M27,22L27,22L5,44l-2.1-2.1L22.8,22L2.9,2.1L5,0L27,22L27,22z\" />\r\n");
      out.write("\t          </svg>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\r\n");
      out.write("\t        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </div><!-- .sample -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t  </div><!-- .c-container -->\r\n");
      out.write("\t</div><!-- .l-wrapper -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"main-content\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("           <div class=\"span4\">\r\n");
      out.write("             <h2>Our Products</h2>\r\n");
      out.write("             <p>Oh…yeah…the guy in the…the $4,000 suit is holding the elevator for a guy who doesn't make that in three months. Come on! Speaking of settling, how's Ann? He's a regular Freddie Wilson, that one.</p>\r\n");
      out.write("             <p class=\"text-center\"><a class=\"btn\" href=\"index.html\">Read more</a></p>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("           <div class=\"span4\">\r\n");
      out.write("             <h2>We Love You! <small>so much</small></h2>\r\n");
      out.write("             <p>I mean, it's one banana, Michael. What could it cost, ten dollars? It's sort of like going from prime rib to… I don't know… weird brother of prime rib. I hear the jury's still out on science. <strong>Check out banner, Michael!</strong></p>\r\n");
      out.write("             <p class=\"text-center\"><a class=\"btn btn-primary\" href=\"index.html\">Primary button</a></p>\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("           <div class=\"span4\">\r\n");
      out.write("             <h2>Headline Here</h2>\r\n");
      out.write("             <p>Obviously this blue part here is the land. Let the great experiment begin! But I'm the oldest. The matriarch if you will. She's always got to wedge herself in the middle of us so that she can control everything. Yeah. Mom's awesome. Maybe we should call her?</p>\r\n");
      out.write("             <p class=\"text-center\"><a class=\"btn\" href=\"index.html\">Read more</a></p>\r\n");
      out.write("           </div>\r\n");
      out.write("        </div><!-- @end .row -->\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t");
      out.print( tableHTML );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <h2>SNES in Dribbble Shots</h2>\r\n");
      out.write("        <div class=\"alert alert-info\">\r\n");
      out.write("          <strong>Note:</strong> Each shot is linked to the original source.\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row-fluid\">\r\n");
      out.write("          <ul class=\"thumbnails\">\r\n");
      out.write("            <li class=\"span4\">\r\n");
      out.write("              <a href=\"http://dribbble.com/shots/39065-snes-controller\" class=\"thumbnail\" target=\"_blank\">\r\n");
      out.write("              <img src=\"https://i.imgur.com/Q4bxBmd.png\" alt=\"snes controller dribbble shot\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"span4\">\r\n");
      out.write("              <a href=\"http://dribbble.com/shots/525128-Micons-Series-2-SNES\" class=\"thumbnail\" target=\"_blank\">\r\n");
      out.write("              <img src=\"https://i.imgur.com/uQLkghZ.png\" alt=\"minicon series2 snes console\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"span4\">\r\n");
      out.write("              <a href=\"http://dribbble.com/shots/633186-The-Game\" class=\"thumbnail\" target=\"_blank\">\r\n");
      out.write("              <img src=\"https://i.imgur.com/vLg6MDV.png\" alt=\"snes video game cartridge shot\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!-- @end .row-fluid -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row-fluid\">\r\n");
      out.write("          <ul class=\"thumbnails\">\r\n");
      out.write("            <li class=\"span6\">\r\n");
      out.write("              <a href=\"http://dribbble.com/shots/758735-Oh-Oh-Please-Amaze-Me-Detail-IV\" class=\"thumbnail\" target=\"_blank\">\r\n");
      out.write("              <img src=\"https://i.imgur.com/SS8Kiln.png\" alt=\"dribbble shots super nintendo\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"span6\">\r\n");
      out.write("              <a href=\"http://dribbble.com/shots/436565-Jaku-Console-Wars\" class=\"thumbnail\" target=\"_blank\">\r\n");
      out.write("              <img src=\"https://i.imgur.com/y3M2d7p.png\" align=\"dribbble console wars super nintendo design\">\r\n");
      out.write("              </a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!-- @end .row-fluid -->\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("      </div><!-- @end .container -->\r\n");
      out.write("    </div><!-- @end #main-content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <p>Simple layout design for <a href=\"http://blog.teamtreehouse.com/\">Treehouse Blog</a>.</p>\r\n");
      out.write("        <p>Feel free to download and use these codes for any basic template layout.</p>\r\n");
      out.write("        <p><small>Website code structured with <a href=\"https://twitter.github.io/bootstrap/\">Twitter Bootstrap</a>. Background image credits to <a href=\"http://www.flickr.com/photos/fjolnir/2342246699/\">Fjölnir Ásgeirsson</a>. Sample content via <a href=\"http://bluthipsum.com/\">Bluth Ipsum</a>.</small></p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
